config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'ideas#index'
  resources :ideas do 
    resources :reviews, only: [:create, :destroy]
  end

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      # if user.admin?
      #can :manage, :all
    #   else
    #     can :read, :all
     # end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

    alias_action(:create, :read, :update, :delete, to: :crud)

    can(:crud, Idea) do |idea| 
      user == idea.user
    end

    can(:crud, Review) do |review| 
      user == review.user
    end

  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
class Idea < ApplicationRecord

  belongs_to :user, optional: true
  has_many :reviews, dependent: :destroy

  validates :title, presence: true, uniqueness: true
  validates :description, presence: true, length: { minimum: 20 }

end

app/models/review.rb
class Review < ApplicationRecord

  belongs_to :idea
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord

  has_many :ideas, dependent: :nullify
  has_many :reviews, dependent: :nullify

  has_secure_password
  
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def current_user 
    @current_user ||= User.find_by_id session[:user_id]
  end 

  helper_method :current_user


  def user_signed_in?
    current_user.present?
  end

  helper_method :user_signed_in?
  

  def authenticate_user!
    redirect_to new_session_path, notice: 'Please sign in' unless user_signed_in? 
  end

end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_idea, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user!, only: [:edit, :update, :destroy]
  
  def new 
    @idea = Idea.new
  end

  def index 
    @ideas = Idea.all
  end

  def create 
    @idea = Idea.new idea_params
    @idea.user = current_user
    
    if @idea.save
      flash[:notice] = "Idea created successfully"
      redirect_to idea_path(@idea)
    else
      render :new
    end
  end

  def show 
    @review = Review.new
    @reviews = @idea.reviews.order(created_at: :desc)
  end

  def edit 
  end

  def update 
    if @idea.update idea_params
      flash[:notice] = "Idea edited successfully"
      redirect_to idea_path(@idea)
    else 
      render :edit
    end
  end

  def destroy 
    @idea.destroy
    redirect_to ideas_path
  end


  private 

  def find_idea 
    @idea = Idea.find params[:id]
  end

  def idea_params 
    idea_params = params.require(:idea).permit(:title, :description)
  end

  def authorize_user!
    redirect_to idea_path(@idea), alert: "Impossible Action" unless can?(:crud, @ideas)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    before_action :authenticate_user!

  def create 
    @idea = Idea.find params[:idea_id]
    @review = Review.new review_params
    @review.idea = @idea
    @review.user = current_user

    if @review.save
      flash[:notice] = "Review successfully created"
      redirect_to idea_path(@idea)
    else
      redirect_to idea_path(@idea)
    end

  end

  def destroy 
    @idea = Idea.find params[:idea_id]
    @review = Review.find params[:id]
    if can?(:crud, @review)
      @review.destroy
      redirect_to idea_path(@idea), notice: 'Review deleted'
    else 
      redirect_to idea_path(@idea), alert: "Oops! Can't do that"
    end
  end

  private 

  def review_params
    params.require(:review).permit(:body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create 
    @user = User.find_by_email params[:email]
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Logged in'
    else
      flash[:alert] = 'Wrong email or password'
      render :new
    end
  end

  def destroy 
    session[:user_id] = nil
    redirect_to root_path, notice: 'Logged out'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new 
    @user = User.new
  end

  def create 
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Logged in"
    else 
      render :new
    end
  end


  private 

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ideas/_form.html.erb
<% if @idea.errors.any? %>
  <ul>
    <% @idea.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end%>


<%= form_for @idea do |f| %>
  <div>
    <%= f.label :title %> <br>
    <%= f.text_field :title %>
  </div><br>
  <div>
    <%= f.label :description %> <br>
    <%= f.text_area :description, size: "50x4" %>
  </div><br>
  <%= f.submit %>
<% end %>

app/views/ideas/edit.html.erb
<h1>Edit Your Idea</h1>

<%= render 'form' %>

app/views/ideas/index.html.erb
<h1>Listing all Ideas</h1>

<% @ideas.each do |idea| %>
  <div>
    <h3><%= link_to idea.title, idea_path(idea) %></h3>
    <p><%= idea.description %></p>
  </div><br>
<% end %>

app/views/ideas/new.html.erb
<h1>Got an Idea?</h1>

<%= render 'form' %>

app/views/ideas/show.html.erb
<h1>Great Idea..</h1>

<h2><%= @idea.title %></h2>

<p><%= @idea.description %></p>

<%= link_to "Edit", edit_idea_path(@idea) %>
<%= link_to "Delete", idea_path(@idea), method: :delete, data: { confirm: "Are you sure?"} %>

<hr>

<h3>Add a review:</h3>

<%= form_with model: [@idea, @review], local: true do |f| %>
  <div>
    <%= f.text_area :body, size: '50x5', placeholder: "Your thoughts..." %>
  </div>
  <%= f.submit %>
<% end %>

<br>
<br>

<h4>What others think of this idea</h4>
<% @reviews.each do |review| %>
    <div>
      <p><%= review.body %></p>
    </div>

    <%= link_to 'Delete', idea_review_path(@idea, review), method: :delete, data: { confirm: 'Are you sure you want to delete this review?'} %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to 'Ideas Blog', root_path %>
|
<%= link_to 'New Idea', new_idea_path %>
|
<% if user_signed_in? %>
  Hello <%= current_user.name %> | <%= link_to 'Logout', session_path, method: :delete, data: { confirm: 'Are you sure you want to logout?' } %>
<% else %>
  <%= link_to 'Login', new_session_path %> | <%= link_to 'Sign Up', new_user_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IdeasBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %> <br>

    <%= flash[:notice] || flash[:alert] %>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign up Form</h1>

<%= form_with model: @user, local: true do |f| %>
  <% if @user.errors.any? %>
    <p>
      <%= @users.errors.full_messages.join(', ') %>
    </p>
  <% end %>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
  <div> 
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <%= f.submit "Sign up" %>
<% end %>